### ISSUE TITLE
Week 2 - Compare these two snippet code.

### ISSUE THREAD

**Issue by chientranthien** [duytruong/weekly-question#3]
```
StringBuilder sb = new StringBuilder();
sb.append("happy ");
sb.append("new ");
sb.append("year!");
return sb.toString();
```

```
String message="";
message+= "happy ";
message+= "new ";
message+= "year!";
return message;
```

**Comment by letientai299** [comment]
In what criterias? :v

**Comment by chientranthien** [comment]
the main criteria is memory allocation.

**Comment by duytruong** [comment]
String concatenation expression creates new object that contains the result of concatenation. When you perform repeated String concatenation, the Java compiler **may** [use](http://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.18.1) StringBuffer, StringBuilder or similar technique to reduce the number of intermediate String objects that are created (Because [StringBuilder](https://docs.oracle.com/javase/8/docs/api/java/lang/StringBuilder.html) has a initial capacity, if the length of character sequence contained in the StringBuilder doesn't exceed the capacity, it doesn't need to allocate new internal memory). So there is no difference.

Ref: http://stackoverflow.com/questions/1532461/stringbuilder-vs-string-concatenation-in-tostring-in-java

Btw, which label do you want me to assign?

**Comment by letientai299** [comment]
If we count the memory for call stack and time for string concat to delegate to StringBuilder, then there's difference.

**Comment by chientranthien** [comment]
@duytruong please mark this issue with 'java' label.

**Comment by chientranthien** [comment]
@letientai299 the optimization is decided at compile time not runtime, so there is no difference.

**Comment by letientai299** [comment]
Nice catch. Would be great if we have the relevant links or material on this topic too.

**Comment by chientranthien** [comment]
@letientai299 @duytruong 
This is a good article to refer
https://dzone.com/articles/string-builders-and-smart-compilers

**Comment by duytruong** [comment]
@letientai299 I included inline link in my answer (not SO link)

**Comment by duytruong** [comment]
@chientranthien do you want to close this issue?

**Comment by chientranthien** [comment]
@duytruong yes, please
